name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: infra

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Confirm destroy
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
            echo "Confirmation failed. Type DESTROY to run this workflow."
            exit 1
          fi

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::622703418024:role/terraform_oidc_role
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform fmt 
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy 

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 